### ISSUE TITLE
Default for `command_prefix` is broken

### ISSUE THREAD

**Issue by alexjfisher** [voxpupuli/puppet-puppetwebhook#15]
https://github.com/voxpupuli/puppet-puppetwebhook/blob/c3719a5db01868c50773146edc45bd15b0353f28/data/common.yaml#L19

should be `umask 0022;`?

**Comment by alexjfisher** [comment]
Probably should just be made `Optional` with no default?

**Comment by dhollinger** [comment]
Either is probably fine
