### ISSUE TITLE
https://dl.bintray.com/voxpupuli/rpm/el/8/x86_64/repodata/repomd.xml throws 403

### ISSUE THREAD

**Issue by sgnl05** [voxpupuli/puppet-puppetwebhook#44]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: N/A
- Ruby: N/A
- Distribution: CentOS
- Module version: 2.1.0

## How to reproduce (e.g Puppet code you use)
Use module with default parameters

## What are you seeing
Http error 403 on https://dl.bintray.com/voxpupuli/rpm/el/8/x86_64/repodata/repomd.xml prevents puppetwebhook from being installed

## What behaviour did you expect instead
Normal installation

## Output log
```
Error: Execution of '/usr/bin/dnf -d 0 -e 1 -y install puppet-webhook' returned 1: Error: Failed to download metadata for repo 'voxpupuli': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Error: /Stage[main]/Puppetwebhook::Install/Package[puppet-webhook]/ensure: change from 'purged' to 'present' failed: Execution of '/usr/bin/dnf -d 0 -e 1 -y install puppet-webhook' returned 1: Error: Failed to download metadata for repo 'voxpupuli': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

**Comment by dhollinger** [comment]
bintray shutdown earlier this year. Unless there is a huge need, we won't be updating with new repos for those packages. The code has been updated to pull directly from the releases page of `puppet_webhook`, but the ruby version is being replaced by a simpler version written in Go. 

That one will have packages and should be ready soon.
